service: otenki-run
provider:
  runtime: python3.7
  name: aws
  region: ap-northeast-1
  stage: prod
  timeout: 120

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  create_trello_card:
    handler: lambda_function.lambda_handler
