service: otenki-run
provider:
  name: aws
  region: ap-northeast-1
  stage: prod
  timeout: 120

plugins:
  - serverless-python-requirements

package:
  individually: true

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  create_trello_card:
    runtime: python3.7
    handler: lambda_function.lambda_handler
